### ISSUE TITLE
Server builds are currently broken due to terser

### ISSUE THREAD

**Issue by rpetti** [probot/smee#99] opened 2019-02-02 18:00 UTC
I get the following when attempting to build the latest server code using npm install:

```
Hash: 4120e23763458b11ab1b
Version: webpack 4.29.0
Time: 4425ms
Built at: 02/02/2019 10:51:36 AM
 2 assets
Entrypoint main = main.min.css main.min.js
[13] (webpack)/buildin/global.js 472 bytes {0} [built]
[14] ./src/style.scss 39 bytes {0} [built]
[17] (webpack)/buildin/module.js 497 bytes {0} [built]
[21] ./src/main.js + 7 modules 102 KiB {0} [built]
     | ./src/main.js 195 bytes [built]
     |     + 7 hidden modules
    + 19 hidden modules

ERROR in main.min.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/data/rpetti/git/smee/server/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at TaskRunner.boundWorkers (/data/rpetti/git/smee/server/node_modules/terser-webpack-plugin/dist/TaskRunner.js:68:40)
    at enqueue (/data/rpetti/git/smee/server/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:14)
    at tryCatcher (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/data/rpetti/git/smee/server/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:637:19)
```

This appears to be caused by webpack-contrib/terser-webpack-plugin#66. I was able to work around it by adding terser version 3.14.1 as a dependency in smee server's package.json.

**Comment by JasonEtco** [comment] 2019-02-02 18:36
Thanks for the report @rpetti 🙏 - I'm able to reproduce this as well. We still aren't committing `package-lock.json` 😭 so this kind of thing is inevitable until #90 is done. I'd really like to finish up #93 before making changes though. Will keep my eye on this, and if we can't resolve #93 we'll fix this up 👍

**Comment by rpetti** [comment] 2019-02-02 19:16
Great, thanks!

**Comment by JasonEtco** [comment] 2019-03-31 02:01
This looks like it fixed itself on its own through a patch version of `terser-webpack-plugin`. We still need to resolve #90, but I'm going to close this as it seems to be solved.

**Closed by JasonEtco** 2019-03-31 02:01 UTC
Labels: bug
